# Generated by Django 5.2.7 on 2025-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
